### ISSUE TITLE
Create turn by turn directions screen

### ISSUE THREAD

**Issue by codergrl** [Esri/maps-app-dotnet#11]
- [x] WPF
- [x] UWP
- [x] iOS
- [x] Android

**Comment by mikewilburn** [comment]
Blocked - I'm not able to test this because the auto-suggest results are not appearing when I type a placename or address in the search bar on UWP. Note: this is running the app via Windows. Mara does not see this behavior when running natively on a Windows 10 OS.

**Comment by nCastle1** [comment]
Confirming this is working for Windows UWP. The UWP text field input issue was related to how the Esri Windows 10 images were configured under Parallels.
